### ISSUE TITLE
New Tag Creation Autocomplete

### ISSUE THREAD

**Issue by squant** [schmave/demschooltools#136]
When I tried to create a new tag, the autocomplete offered "create new tag: alumni". I arrowed down to that and created a new tag called "create new tag: alumni" which was not the expected or desired outcome. Already remedied my case and changed tag to "alumni" using "edit tag", but noting here.

Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Windows 10 V1803 17134.407

**Comment by schmave** [comment]
Thanks for the very clear bug report!
