### ISSUE TITLE
Custodia: Time of Attendance

### ISSUE THREAD

**Issue by jmorri20** [schmave/demschooltools#178]
Hello,

Long time user of demschooltools, new user of Custodia. As far as I can tell there is no way of seeing what time of day a person was at school. I see in the report the day they are there and the number of hours, but we often need to check things like "what time did ____ sign in?"  I'm surprised that this info isn't available in the report and so it's possible that I'm missing something. If that ability isn't in there I think it would be a good change. If that functionality is already available could somebody please point me towards how to access that info?

-R from FHS

**Comment by schmave** [comment]
Hi!

If you click on the calendar icon to the left of a person's name, you can see their history of "swipes" for each day by clicking on a day in the calendar view that is shown. 

![Screen Shot 2020-08-27 at 11 31 27 AM](https://user-images.githubusercontent.com/868327/91463064-f0075580-e858-11ea-886b-f75fae681a6a.png)

I find that the best thing to do with Custodia data is to import it into the Attendance tab, which has additional features and lets you see all students' signin times at once. The main downside is that the Attendance tab only stores the first signin and last signout time of the day, so if you have students who frequently leave during the day it might give you inaccurate results. 

There's more info about importing Custodia data into Attendance here:

https://github.com/schmave/demschooltools/wiki/Attendance-tracking

**Comment by jmorri20** [comment]
Thank you very much! For some reason, that data wasn't loading at first but now I see that it is. Sorry for taking up your time! I really like this app. Great work! 

-R

**Comment by schmave** [comment]
No problem, it's pretty confusing sometimes. And there's a bug that causes that screen to fail to load at first. So it's not your fault most likely. Hope it goes well this year.
