### ISSUE TITLE
showing multiple changes to one rule in viewmanualchanges 

### ISSUE THREAD

**Issue by squant** [schmave/demschooltools#190]
One of our rules (300.44) was removed in June 2022 but I forgot if it had passed or not. When I did a search going back a long way to try to confirm that had happened, I just saw the most recent change to the rule from 2020 without ever seeing that it was removed. I'm not sure if there is any broader trouble viewing several changes to one rule.

**Comment by schmave** [comment]
Hmm, I'll take a look! Thanks for the report.

**Comment by schmave** [comment]
Hmm, yeah it looks like [the code](https://github.com/schmave/demschooltools/blob/master/app/controllers/Application.java#L508) only shows the earliest change to a rule in the given time period. I'm not sure why I did it that way, but that seems pretty bad--you can't actually see the full history.

**Comment by schmave** [comment]
I modified this so it shows all changes individually, and shows the date of each change. Seems like a big improvement to me.  Let me know what you think!

**Comment by squant** [comment]
Looks good after a quick check. Thanks for all your work.

**Comment by schmave** [comment]
You're welcome!
