### ISSUE TITLE
Future days this week counting toward "Unknown/Missing Code"

### ISSUE THREAD

**Issue by squant** [schmave/demschooltools#60]
On the "attendance summary" page (eg. http://something.demschooltools.com/attendance# ) the number under "Unknown/Missing Code" number includes the rest of the days in the week.

**Comment by schmave** [comment]
You mean the rest of the days in the current week, right? You enter attendance data very promptly, I guess!

**Comment by squant** [comment]
Yep.  I mean the rest of this week. I don't enter anything though,  Alyssia
does. Isn't urgent, obviously, now that we figured it out.
